version: '3.8'

services:
  postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: vrlingo
      POSTGRES_PASSWORD: vrlingo_pass
      POSTGRES_DB: vrlingo_db
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
